[project]
name = "cs-401r"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "rich>=14.1.0",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
]
